### ISSUE TITLE
Consider Using DI

### ISSUE THREAD

**Issue by vertonghenb** [chrissainty/BlazoredLocalStorage#1]
Have we considered using DI to make it more testable?

**Comment by chrissainty** [comment]
Hi @vertonghenb, apologies for not getting back sooner. I've made the changes to make the service injectable and added some middleware to register the service as well. So you should just need to do `services.AddLocalStorage()` in your startup.cs going forward. I'll get this up to nuget either tonight or tomorrow.

Hope it helps.
